name: pasti_ada
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_number_picker: ^1.0.4
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: assets/app-logo-big.png
  android: true
  ios: true

flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash_light.png
  color_dark: "#000000"
  image_dark: assets/splash_dark.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/